"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page";
import TripProvider from "./context/tripcontext";
import TravelIdProvider from "./context/travelsIdcontext";
import CarProvider from "./context/carcontext";
import Footer from "./components/footer";
import { SessionProvider } from "next-auth/react"; // Import SessionProvider

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Go with SAFAR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          <TripProvider>
            <TravelIdProvider>
              <CarProvider>
                <main>{children}</main>
              </CarProvider>
            </TravelIdProvider>
          </TripProvider>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
